Python/001/entrega14/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('peliculas.urls')),
]

Python/001/peliculas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<pk>', views.DirectorView.as_view(), name='detalles_director'),
    path('pelicula/<pk>', views.PeliculaView.as_view(), name='detalles_pelicula'),
]

Python/001/peliculas/models.py
from django.db import models


class Director(models.Model):
    nombre = models.CharField(max_length=25)
    apellidos = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_defuncion = models.DateField(null=True, blank=True)
    biografia = models.TextField()
    imagen = models.URLField()

    def __str__(self):
        return self.nombre + " " + self.apellidos


class Pelicula(models.Model):
    director = models.ForeignKey('Director', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=25)
    sinopsis = models.TextField()
    duracion = models.PositiveIntegerField()
    imagen = models.URLField()
    anyo = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre

Python/001/peliculas/views.py
# Imports
from django.views import generic

# Models
from .models import Director, Pelicula


class IndexView(generic.ListView):
    template_name = 'peliculas/directores.html'
    model = Director


class DirectorView(generic.DetailView):
    template_name = 'peliculas/director.html'
    model = Director


class PeliculaView(generic.DetailView):
    template_name = 'peliculas/pelicula.html'
    model = Pelicula

Python/001/peliculas/templates/peliculas/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'peliculas/style.css' %}"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <header>
      <h1>{% block header-title %}Directores{% endblock %}</h1>
    </header>
    <main>{% block content %}{% endblock %}</main>
  </body>
</html>

Python/001/peliculas/templates/peliculas/director.html
{% extends "peliculas/base.html" %} {% block title %}Director - {{ director }}{%
endblock %} {% block header-title %}{{ director }}{% endblock %} {% block
content %}
<img
  class="detalle"
  src="{{ director.imagen }}"
  alt="Foto de {{ director }}"
/><br />
<p>
  {{ director.fecha_nacimiento}} - {{director.fecha_defuncion |
  default_if_none:""}}
</p>
<h4>Biografía</h4>
<p>{{ director.biografia | linebreaks }}</p>
<h4>Peliculas</h4>
<table>
  <tr>
    {% for pelicula in director.pelicula_set.all %}
    <td onclick="window.location.href='/pelicula/{{pelicula.id}}'">
      <img src="{{ pelicula.imagen }}" alt="Portada de {{ pelicula }}" /><br />
      <span class="nombre_pelicula">{{ pelicula }}</span>
    </td>
    {% cycle '' '' '
  </tr>
  <tr>
    ' %} {% empty %}
    <td>No hay peliculas aún</td>
    {% endfor %}
  </tr>
</table>
{% endblock %}

Python/001/peliculas/templates/peliculas/directores.html
{% extends "peliculas/base.html" %} {% block title %} Directores {% endblock %}
{% block content %}
<table>
  <tr>
    {% for director in object_list %}
    <td onclick="window.location.href='/{{director.id}}'">
      <img src="{{ director.imagen }}" alt="Foto de {{ director }}" /><br />
      <span class="nombre_director"
        >{{ director }}{% if director.fecha_defuncion %}&dagger;{% endif
        %}</span
      >
    </td>
    {% cycle '' '' '
  </tr>
  <tr>
    ' %} {% empty %}
    <td>No hay directores aún</td>
    {% endfor %}
  </tr>
</table>
{% endblock %}

Python/001/peliculas/templates/peliculas/pelicula.html
{% extends "peliculas/base.html" %} {% block title %}Pelicula - {{ pelicula }}{%
endblock %} {% block header-title %}{{ pelicula }}{% endblock %} {% block
content %}
<img
  class="detalle"
  src="{{ pelicula.imagen }}"
  alt="Portada de {{ pelicula }}"
/><br />
<p><b>Año: </b>{{ pelicula.año}}</p>
<h4>Sinopsis</h4>
<p>{{ pelicula.sinopsis | linebreaks }}</p>
{% endblock %}